name: Build the current version

on: [ workflow_dispatch ]

jobs:
  Run-Build:
    runs-on: ubuntu-latest
    name: Build on Mac OS
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install --no-optional
      - run: npm run build
